name: Create Release

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'ID of the successful build workflow run to use (required)'
        required: true
        type: string
      version:
        description: 'Version to release (e.g., 0.0.1)'
        required: true
        type: string

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-test.yml
          run_id: ${{ github.event.inputs.workflow_run_id }}
          name: build-artifacts
          path: build/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          files: build/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          retention-days: 5
